version: '3'

services:
  postgres:
    image: postgres:14.6-alpine
    container_name: service-database-container
    ports:
      - '5432:5432'
    environment:
      POSTGRES_HOST_AUTH_METHOD: trust
      POSTGRES_USER: service-user
